### ISSUE TITLE
script alarm creation

### ISSUE THREAD

**Issue by micaelaroberts** [newsdev/metrics#31]

**Comment by oldwestaction** [comment]
![](http://img1.wikia.nocookie.net/__cb20130303050918/adventuretimewithfinnandjake/images/3/36/Gentle_lasers.gif)

made some group progress on this today!

**Comment by 4nj4li** [comment]
done for ec2 instances.  not done yet for elasticache, rds, or mongo.  will need some sort of naming convention in place to find the instances to monitor (rather than monitoring all of them).  
anyway, search here for 'cluster' to see the ec2 monitors, minus the 'oscars' one:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarm:alarmFilter=ANY

alarms are regenerated at 48 and 18 past each hour, in case we decide to change thresholds for any type. we should discuss how to go about changing thresholds -- right now we'd need to deploy code (which isn't so bad in dockerland), but it'd be nice to have an admin for this, or maybe store values in aws as name-value pairs:  https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Instances:instanceState=running;sort=desc:tag:Name

though it doesn't seem like you can update those values en masse.

one more thing to note -- all metrics are not necessarily available for all the instances that you see alarms for yet.  the next time those instances are rebooted, we'll start getting custom metrics (ie disk utilization, etc) for them every minute.
